# 450+ Practice Questions That Will Make You a Pandas, NumPy, and SQL Pro!

Author: Avi Chawla

LinkedIn: https://www.linkedin.com/in/avi-chawla/

Read my blogs here: https://medium.com/@avi_chawla

## Introduction

This notebook has been created for you to practice three of the most common tools used in building any machine learning or data science applications, i.e., Pandas, NumPy, and SQL!

The practice questions provided will serve as a great resource for those who are looking to familiarize themselves with some of the most common functions used in these tools. 

Appropriate descriptions have been provided for all the questions in this entire exercise which will help you navigate through this exercise easily. If a dataset is to be loaded in the python environment, that has also been provided for you. You can find it on the right panel in the Files section. Do NOT delete any of the files/folders listed there. 

The whole exercise has been divided into nine separate notebooks. Below are the links to all the other notebooks for you to jump from one notebook to another:

- **Pandas**

1. Pandas Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-1-d693ac55-6455-40cf-ae34-867c6a02014e/%2Fnotebook.ipynb) 
2. Pandas Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-dataset-7e3b6755-5d4b-464b-9b75-9c84667ae3bd/%2Fnotebook.ipynb) 

3. Pandas Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-part-2-adc5a3ee-5f61-4725-8e46-ccb07899acfc/%2Fnotebook.ipynb)

4. Pandas Notebook 4: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-after-employee-f84e02a1-fb6a-428e-af90-8dd99855749a/%2Fnotebook.ipynb)

- **NumPy**

1. NumPy Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Numpy-part-1-9b9979f2-b708-4292-b466-3d0157564c91/%2Fnotebook.ipynb) **(This Notebook)** 

2. NumPy Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-2-4456411e-2ddd-426d-8027-4881080027db/%2Fnotebook.ipynb)

3. NumPy Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-3-e6587114-b580-4249-b599-540de859e603/%2Fnotebook.ipynb)

- **SQL**

1. SQL Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-1-eac9d782-a9b1-4e84-a1f9-af14080a6121/%2Fnotebook.ipynb)

2. SQL Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-2-1914b214-be03-44a1-be63-ad99e98be639/%2Fnotebook.ipynb)

## How to use this notebook?

At the top right corner, you will find a Duplicate button. This will allow you to create a unique notebook for your own practice and write solutions to the question listed in this notebook.  

If you face any issues or have any feedback, feel free to reach out to me (Avi Chawla) either on Linkedin: https://www.linkedin.com/in/avi-chawla/ or write an email to avi@dsscholar[dot]com. 

Let's begin 🚀!

# NumPy Notebook 1

In [1]:
import pandas as pd
import numpy as np

## Create a Numpy Array

### 1. Create a NumPy array from a python list

In [2]:
a = [1, 2, 3]

np_array = np.array(a)
print(np_array)

[1 2 3]


### 2. Print the type of the array created above

In [3]:
type(np_array)

numpy.ndarray

### 3. Create a NumPy array from a python list of lists

In [4]:
a = [[1,2,3], [4,5,6]]

np_array = np.array(a)
print(np_array)

[[1 2 3]
 [4 5 6]]


### 4. Print the type of the array created above

In [5]:
type(np_array)

numpy.ndarray

### 5. While creating the numpy array, specify the data type as float32.

In [6]:
a = [[1,2,3], [4,5,6]]

np_array = np.array(a, dtype="float32")
print(np_array)

[[1. 2. 3.]
 [4. 5. 6.]]


### 6. Create a NumPy array of Zeros

In [7]:
np_array = np.zeros(2)
print(np_array)

[0. 0.]


### 7. Create a multi-dimensional NumPy array of Zeros

In [8]:
np_array = np.zeros([2, 2])
print(np_array)

[[0. 0.]
 [0. 0.]]


### 8. Create a NumPy array of Ones

In [9]:
np_array = np.ones(2)
print(np_array)

[1. 1.]


### 9. Create a multi-dimensional NumPy array of Ones

In [10]:
np_array = np.ones([2, 2])
print(np_array)

[[1. 1.]
 [1. 1.]]


### 10. Create an Identity Numpy Array of order 3

In [11]:
np_array = np.ones([3, 3])
print(np_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 11-13. Create an equally spaced Numpy Array with a specific step

### Generate values from start=0 to stop=10 with step=1:

In [12]:
np_array = np.arange(1, 10)
print(np_array)

[1 2 3 4 5 6 7 8 9]


### Generate values from start=5to stop=11 with step=1:

In [13]:
np_array = np.arange(5, 11)
print(np_array)

[ 5  6  7  8  9 10]


### Generate values start=5 to step=11 with step=2.

In [14]:
np_array = np.arange(5, 11, 2)
print(np_array)

[5 7 9]


### 14-15. Create an equally spaced Numpy Array with a specific array size

Generate a numpy array of size 5 with start=0 to stop=10

In [15]:
np_array = np.linspace(0, 10, 5)
print(np_array)

[ 0.   2.5  5.   7.5 10. ]


Generate a numpy array of size 5 with start=5 to stop=7

In [16]:
np_array = np.linspace(5, 7, 5)
print(np_array)

[5.  5.5 6.  6.5 7. ]


### 16-17. Generate a random numpy array 

Generate a random integer array of size 5 with start=0 to stop=10

In [17]:
np_array = np.random.randint(0, 10, 5)
print(np_array)

[6 0 0 1 4]


Generate a random float array of size 10

In [18]:
np_array = np.random.rand(10)
print(np_array)

[0.53537717 0.74071756 0.79670482 0.02562953 0.50713262 0.52226386
 0.47929535 0.02862564 0.81319133 0.94997461]


### 18-19. Generate NumPy Array from a Pandas Series using two methods

### Method 1:

In [19]:
s = pd.Series([1,2,3,4], name = "col")

np_array = np.array(s)
print(np_array)

[1 2 3 4]


### Method 2:

In [20]:
s = pd.Series([1,2,3,4], name = "col")

np_array = s.to_numpy()
print(np_array)

[1 2 3 4]


## NumPy Array Manipulation Methods

### 20-21. Shape of the NumPy Array in two ways

### Method 1:

In [21]:
a = np.ones((2, 3))

shape_of_a = a.shape
print(shape_of_a)

(2, 3)


### Method 2:

In [22]:
a = np.ones((2, 3))

shape_of_a = a.shape
print(shape_of_a)

(2, 3)


### 22. Reshape the NumPy Array to 2*5

In [23]:
a = np.arange(10)

np_array = a.reshape(2, 5)
print(np_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 23-24. Transpose the NumPy Array in two ways

Method 1:

In [24]:
a = np.array([[1,2,3], [4,5,6]])

np_array = a.T
print(np_array)

[[1 4]
 [2 5]
 [3 6]]


### Method 2:

In [25]:
a = np.array([[1,2,3], [4,5,6]])

np_array = a.transpose()
print(np_array)

[[1 4]
 [2 5]
 [3 6]]


### 25-27. Concatenate multiple NumPy arrays to form one NumPy Array

### Concatenate row-wise

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.concatenate((a, b))
print(np_array)

[[1 2]
 [3 4]
 [5 6]]


Concatenate column-wise

In [27]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.concatenate((a, b.T), axis=1)
print(np_array)

[[1 2 5]
 [3 4 6]]


### Concatenate to generate a flat NumPy Array

In [28]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.concatenate((a, b)).flatten()
print(np_array)

[1 2 3 4 5 6]


### 28-29. Concatenate using vstack() and hstack()

### vstack()

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.vstack((a, b))
print(np_array)

[[1 2]
 [3 4]
 [5 6]]


### hstack()

In [30]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.hstack((a, b.T))
print(np_array)

[[1 2 5]
 [3 4 6]]


### 30. Flatten NumPy Array

In [31]:
a = np.array([[1,2], [3,4]])

np_array = a.flatten()
print(np_array)

[1 2 3 4]


### 31-33. Print Unique Elements of a NumPy Array

In [32]:
a = np.array([[1,2], [3,2]])

np_array = np.unique(a)
print(np_array)

[1 2 3]


return unique rows

In [33]:
a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.unique(a, axis=0)
print(np_array)

[[1 2 3]
 [2 3 4]]


return unique columns

In [34]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])

np_array = np.unique(a, axis=1)
print(np_array)

[[1 3]
 [1 3]
 [1 4]]


### 34. Squeeze the NumPy Array

In [35]:
a = np.array([[[0], [1], [2]]])

np_array = np.squeeze(a)
print(np_array)

[0 1 2]


### 35. Get Python list from NumPy array

In [36]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])

py_list = a.tolist()
print(py_list)

[[1, 1, 3], [1, 1, 3], [1, 1, 4]]


Great Job solving this notebook. Go to NumPy Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-2-4456411e-2ddd-426d-8027-4881080027db/%2Fnotebook.ipynb)


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=9b9979f2-b708-4292-b466-3d0157564c91' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>